import { z } from "https://esm.sh/zod@3.22.4";
import { PlayerConfigEntrySchema } from "./playerConfigEntry.ts";
import { RankSchema } from "./rank.ts";
// @deno-types="npm:@types/lodash"
import _ from "npm:lodash@4.17.21";
import { PlayerConfig } from "./playerConfig.ts";

export type QueueType = z.infer<typeof QueueTypeSchema>;
export const QueueTypeSchema = z.enum(["solo", "flex"]);

export type MatchState = z.infer<typeof MatchStateSchema>;
export const MatchStateSchema = z.strictObject({
  // a way to uniquely identify this entry
  // generated by the application
  uuid: z.string(),
  // the time that this was added to the state
  added: z.string().pipe(z.coerce.date()),
  // the match id from the Riot API
  matchId: z.number(),
  player: PlayerConfigEntrySchema,
  rank: RankSchema,
  queue: QueueTypeSchema,
});

export type State = z.infer<typeof StateSchema>;
export const StateSchema = z.strictObject({
  gamesStarted: z.array(MatchStateSchema),
});

export function getPlayersInGame(players: PlayerConfig, state: State) {
  return _.filter(players, (player) =>
    _.some(
      state.gamesStarted,
      (game) =>
        game.player.league.leagueAccount.accountId ===
        player.league.leagueAccount.accountId
    )
  );
}

export function getPlayersNotInGame(players: PlayerConfig, state: State) {
  return _.reject(players, (player) =>
    _.some(
      state.gamesStarted,
      (game) =>
        game.player.league.leagueAccount.accountId ===
        player.league.leagueAccount.accountId
    )
  );
}
