version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    assignees: shepherdjerred
    reviewers: shepherdjerred
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    assignees: shepherdjerred
    reviewers: shepherdjerred
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
  - package-ecosystem: "npm"
    directory: "/packages/backend"
    schedule:
      interval: "weekly"
      day: "sunday"
    assignees: shepherdjerred
    reviewers: shepherdjerred
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
  - package-ecosystem: "npm"
    directory: "/packages/frontend"
    schedule:
      interval: "weekly"
      day: "sunday"
    assignees: shepherdjerred
    reviewers: shepherdjerred
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
  - package-ecosystem: "npm"
    directory: "/packages/data"
    schedule:
      interval: "weekly"
      day: "sunday"
    assignees: shepherdjerred
    reviewers: shepherdjerred
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
  - package-ecosystem: "npm"
    directory: "/packages/preview"
    schedule:
      interval: "weekly"
      day: "sunday"
    assignees: shepherdjerred
    reviewers: shepherdjerred
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
