version: 2

groups:
  production-dependencies:
    dependency-type: "production"
  development-dependencies:
    dependency-type: "development"

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "npm"
    directory: "/packages/backend"
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "npm"
    directory: "/packages/frontend"
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "npm"
    directory: "/packages/data"
    schedule:
      interval: "weekly"
      day: "sunday"
