repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        additional_dependencies:
          - "prettier@3.2.4"
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v9.0.0-beta.0"
    hooks:
      - id: eslint
        files: \.[jt]sx?$
        types: [file]
        additional_dependencies:
          - "eslint@8.34.0"
          - "eslint-config-prettier@8.5.0"
          - "@typescript-eslint/eslint-plugin@5.53.0"
          - "@typescript-eslint/parser@"
          - "babel-eslint@6.1.2"
