app = "lavalink-prod"
primary_region = "sea"

[build]
  image = "ghcr.io/lavalink-devs/lavalink:4"

[[services]]
  internal_port = 2333
  protocol = "tcp"
  [[services.ports]]
    handlers = ["http"]
    port = "80"
  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

[env]
  SERVER_PORT=2333
  LAVALINK_SERVER_SOURCES_YOUTUBE=true
