name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions-setup@v1.0.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}
      - name: build image
        run: earthly --ci -P +ci
      - name: push image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: earthly --ci push -P +ci
